### ISSUE TITLE
No CAPTCHA in discussion plugin

### ISSUE THREAD

**Issue by lucker999** [dokufreaks/plugin-discussion#173]
But CAPTCHA works fine for registration. Running 2014-09-29d "Hrun"

I also tested the combination of the plugins on freshly installed dokuwiki (the same latest release) with the only two mentioned plugins - the same results. CAPCHA works fine (with every mode) for registration, but not even shows up for comments (discussion plugin). Additionally, when I try to post a comment the page says "CAPTCHA doesn't match" mean I didn't enter the correct answer.

Could you please help to resolve the issue?

**Comment by SteveLowe** [comment]
I ran into the same problem today, using 2014-09-29d.

Looks like it was caused by this change in the captcha plugin:
splitbrain/dokuwiki-plugin-captcha@7218f96ceebeadf8d318824c7833a4bda6f325c9
(as the HTML_EDITFORM_INJECTION event no longer exists)

Add this to near the end of the _form function in syntax.php does fix it
```php
    <?php
    $captcha = $this->loadHelper('captcha');
    if ($captcha) {
        ptln($captcha->getHTML());
    }
    ?>
```
