### ISSUE TITLE
Show time in client's timezone, not in server's one.

### ISSUE THREAD

**Issue by dimonomid** [dokufreaks/plugin-discussion#194]
Would it be possible to display comment time in client's timezone? Currently, it is displayed in server timezone, independently of where client is, which is quite confusing. Or, at least the easiest option: don't show time, show date only.

**Comment by Klap-in** [comment]
Hiding the time is not a good solution.
If there is a plugin that could convert dates (e.g. with javascript, which eventually might require an additional tag) to client dates I could try to support that. But I will not implement this directly in this plugin.

**Comment by dimonomid** [comment]
Of course, hiding the time is not a good solution. But I assume that if such an obvious feature as displaying timestamps in client time wasn't implemented already, there must be the reasons for that (what I can think of is the unwillingness to use JavaScript).

If so, this feature is unlikely to be implemented soon. And for me, hidden time is better than wrong time (I use discussion plugin on the site which gets visited by people from different countries, and it's not convenient for all of them to see the same server time)

**Comment by Klap-in** [comment]
Sofar I haven't seen any request for using client timezone for dates instead of timezone setted global at the server.

Dates are used at many places, so it will take some effort to update the displayed dates everywhere to an date that an format that depends on the viewing user. 

For me a JavaScript solution is welcome. Especially if it is opt-in by installing it as plugin. But sofar I have seen JavaScript solutions that update date appearance it requires also that server site a tag is added to date, such that JavaScript will recognize it. As explained, that part will take some effort as well. [ javascript stuff that modify the date, I have seen only for changing a date in to something like `1 min`, `2 hours`, `today`, `yesterday`, etc.

DokuWiki has a function `dformat()`, maybe we could extend that a bit with something that help javascript stuff. However, this function is only used sometimes, not always. https://github.com/splitbrain/dokuwiki/search?p=6&q=dformat&utf8=%E2%9C%93

( only related plugin spotted sofar is: https://www.dokuwiki.org/plugin:localdate - very outdated, and includes only a date in to wiki text)

**Comment by Klap-in** [comment]
If some extra classes or a extra bit of data is needed in the html for supporting a plugin that is fine for me. However, I will not implement this feature directly because it will make the code of the plugin to complicated.
