### ISSUE TITLE
Is it possible to have just one Discussion page?

### ISSUE THREAD

**Issue by atlarep** [dokufreaks/plugin-discussion#212]
I want all the discussions to happen in one single page, regardless of where users are when they click 'Discussion'.
Is this possible?

**Comment by Klap-in** [comment]
It is not an option of this plugin.

This sounds more that you like to add an url to your discussion page. You can add some stuff to the end of the page-content by using `pagefooter.html` (if you are using the 'dokuwiki' template, otherwise you have to modify the template directly). See also https://www.dokuwiki.org/template:dokuwiki#supported_include_hooks
